[package]
name = "vernier-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.12.0"
vernier-core = { path = "../vernier-core" }
vulkano = "0.35.2"
vulkano-shaders = "0.35.0"

[dev-dependencies]
approx = "0.5.1"
nalgebra = "0.35.0"
vernier-camera = { path = "../vernier-camera" }
vernier-cpu = { path = "../vernier-cpu" }
vernier-patterns = { path = "../vernier-patterns" }
vernier-pose = { path = "../vernier-pose" }
