[package]
name = "vernier-render"
version = "0.1.0"
edition = "2024"

[dependencies]
vernier-core = { path = "../vernier-core" }
vulkano = "0.35.2"
vulkano-shaders = "0.35.0"
smallvec = "1.8"

[dev-dependencies]
vernier-patterns = { path = "../vernier-patterns", features = ["vulkan"] }
image = "0.25"
